/**
 * Centralized string literals for SAFERCALLER.
 *
 * Rules:
 *   - No user-facing string should be hardcoded in a component.
 *   - Keep the shape flat-per-screen; deep nesting hurts find/replace.
 *   - When in doubt, add a new key — duplicates across screens are fine
 *     until a translation pass collapses them.
 *   - This is currently the English source-of-truth. A future i18n pass
 *     will wrap each value in `t(...)` and load by locale.
 */
export const STRINGS = Object.freeze({
  app: Object.freeze({
    name: 'SAFERCALLER',
    nameSplit: { left: 'SAFER', right: 'CALLER' },
    tagline: 'AI-Powered Call Protection',
  }),

  common: Object.freeze({
    continue: 'Continue →',
    cancel: 'Cancel',
    save: 'Save',
    saveDraft: 'Save Draft',
    skip: 'Skip',
    skipForNow: 'Skip for now →',
    back: 'Back',
    next: 'Next',
    submit: 'Submit',
    confirm: 'Confirm',
    delete: 'Delete',
    edit: 'Edit',
    done: "I'm Done",
    retry: 'Retry',
    loading: 'Loading…',
    search: 'Search',
    filter: 'Filters ▾',
    sort: 'Sort',
    change: 'Change',
    view: 'View →',
    viewAll: 'View all →',
    start: 'Start →',
    yes: 'Yes',
    no: 'No',
    or: 'or',
    addPlus: 'Add +',
    postPlus: 'Post +',
    settings: 'Settings',
    profile: 'Profile',
    signOut: 'Sign Out →',
    upgrade: 'Upgrade',
  }),

  status: Object.freeze({
    safe: 'Safe',
    flagged: 'Flagged',
    unknown: 'Unknown',
    pending: 'Pending',
    open: 'Open',
    underReview: 'Under Review',
    reviewing: 'Reviewing',
    resolved: 'Resolved',
    highRisk: 'HIGH RISK',
    lowTrust: 'Low trust score',
    online: 'Online',
    offline: 'Offline',
    verified: 'Verified',
    unverified: 'Unverified',
  }),

  splash: Object.freeze({
    selectLanguage: 'Select Language',
    english: 'English',
    moreLanguages: 'More languages coming soon',
    freshInstallNote: 'Each fresh install creates a new account',
  }),

  signup: Object.freeze({
    title: 'Create your account',
    subtitle: 'Verify your phone to get started.',
    phoneLabel: 'Phone Number',
    phonePlaceholder: '98765 43210',
    emailLabel: 'Email Address',
    emailPlaceholder: 'you@email.com',
    sendOtp: 'Send OTP →',
    alreadyHaveAccount: 'Already have an account? Sign In',
    stepIndicator: '2 of 3',
    socialGoogle: 'Google',
    socialApple: 'Apple',
    socialFacebook: 'Facebook',
  }),

  otp: Object.freeze({
    title: 'Enter OTP',
    sentTo: 'Sent to',
    change: 'Change',
    resendIn: 'Resend OTP in',
    verify: 'Verify →',
    privacyNote: 'Your number is never shared publicly.',
    boxPlaceholder: '–',
  }),

  profileSetup: Object.freeze({
    title: 'Tell us about you',
    subtitle: 'Used for People Search and Classifieds.',
    stepIndicator: 'Step 3 of 3',
    addPhoto: 'Add Photo',
    goOnline: 'Go Online',
    goOnlineSub: 'Make your profile discoverable',
    labels: Object.freeze({
      dob: 'DOB',
      gender: 'Gender',
      location: 'Location',
      religion: 'Religion',
      maritalStatus: 'Marital Status',
      profession: 'Profession',
      subProfession: 'Sub-Profession',
      yearlyIncome: 'Yearly Income',
    }),
    aiBadge: 'AI Updated',
  }),

  verification: Object.freeze({
    title: 'Verify Your Identity',
    subtitle: 'Required to build trust on SAFERCALLER.',
    encryptedNote: 'Your data is encrypted and never shared.',
    liveness: Object.freeze({
      title: 'Liveness Video',
      sub: 'Record 10s saying your name.',
    }),
    idProof: Object.freeze({
      title: 'ID Proof',
      sub: 'Show government ID in camera.',
    }),
    thumbprint: Object.freeze({
      title: 'Thumbprint',
      sub: 'Biometric scan for secure login.',
    }),
  }),

  dialer: Object.freeze({
    greetingMorning: 'Good morning 👋',
    greetingAfternoon: 'Good afternoon 👋',
    greetingEvening: 'Good evening 👋',
    blockedToday: (n) => `${n} spam calls blocked today`,
    trustScoreLabel: 'Your Trust Score',
    trustGood: 'Good',
    trustFair: 'Fair',
    trustPoor: 'Poor',
    numberPlaceholder: 'Enter number…',
    chips: Object.freeze({
      idVerified: 'ID Verified',
      liveness: 'Liveness',
      phone: 'Phone',
    }),
  }),

  incomingCall: Object.freeze({
    incomingCall: 'Incoming Call',
    unknownCaller: 'Unknown Caller',
    flagBanner: 'FLAGGED — 12 scam reports',
    flagDetail: 'Reported for UPI Fraud by multiple users.',
    aiReceptionist: 'AI Receptionist',
    aiReceptionistSub: 'Auto-answer & ask purpose',
    block: 'Block',
    decline: 'Decline',
    answer: 'Answer',
    gestureHint: 'Flip phone to decline · Raise to answer',
  }),

  callLogs: Object.freeze({
    title: 'Recents',
    sectionToday: 'Today',
    sectionYesterday: 'Yesterday',
    sectionEarlier: 'Earlier',
    filters: Object.freeze({
      all: 'All',
      missed: 'Missed',
      scamBlocked: 'Scam Blocked',
      recorded: 'Recorded',
      receptionist: 'Receptionist',
    }),
    pillSafe: 'Safe',
    pillFlagged: 'Flagged',
    directionIncoming: 'Incoming',
    directionOutgoing: 'Outgoing',
    directionMissed: 'Missed',
  }),

  scam: Object.freeze({
    reportTitle: 'Report a Scam',
    databaseTitle: 'Scam Database',
    warningBanner: 'Reports are anonymous. Scammer will be notified to resolve.',
    submit: 'Submit Report →',
    descPlaceholder: 'Explain what happened…',
    uploadHeading: 'Upload Proof (up to 6)',
    uploadSub: '6 file types accepted',
    uploadTypes: 'Photos · Audio · Video · Screenshots · Docs',
    searchPlaceholder: 'Search name, number, keyword…',
    resultsCount: (n, q) => `${n} results for '${q}'`,
    fab: '+ Report',
    labels: Object.freeze({
      scammerName: "Scammer's Name",
      phoneNumber: 'Phone Number',
      email: 'Email Address',
      location: 'Location',
      category: 'Scam Category',
      website: 'Website / Company Name',
      socialLinks: 'Social Media Links',
      description: 'Describe the Scam',
    }),
    categories: Object.freeze({
      phishing: 'Phishing',
      upiFraud: 'UPI Fraud',
      fakeJobs: 'Fake Jobs',
      romance: 'Romance Scam',
      investment: 'Investment Fraud',
      other: 'Other',
    }),
  }),

  classifieds: Object.freeze({
    feedTitle: 'Classifieds',
    createTitle: 'Create Listing',
    voicePlaceholder: "Say 'Find nearest plumber'…",
    nearYou: 'Near You',
    postListing: 'Post Listing →',
    autoExpireNote: 'Listing auto-expires after 1 year. Re-confirm annually.',
    useMyLocation: 'Use my location',
    chips: Object.freeze({
      all: 'All',
      plumbing: 'Plumbing',
      electrical: 'Electrical',
      tutoring: 'Tutoring',
      vehicles: 'Vehicles',
      electronics: 'Electronics',
    }),
    typeProduct: 'Product',
    typeService: 'Service',
    conditionNew: 'New',
    conditionUsed: 'Used',
    conditionRefurbished: 'Refurbished',
    contactCall: 'Call',
    contactChat: 'Chat',
    contactBoth: 'Both',
    labels: Object.freeze({
      title: 'Title',
      description: 'Description',
      category: 'Category',
      subcategory: 'Subcategory',
      price: 'Price',
      condition: 'Condition',
      contactMethod: 'Contact Method',
      location: 'Location',
      tags: 'Tags',
    }),
  }),

  people: Object.freeze({
    title: 'People Search',
    placeholder: 'Search by name, profession…',
    sortRelevance: 'Sort: Relevance ▾',
    showingResults: (n) => `Showing ${n} results`,
    chat: 'Chat',
    call: 'Call',
    viewProfile: 'View Profile',
  }),

  chat: Object.freeze({
    listTitle: 'Conversations',
    inputPlaceholder: 'Type a message…',
    online: 'Online',
    typing: 'Typing…',
    reReference: 'Re:',
    delivered: '✓✓',
  }),

  more: Object.freeze({
    title: 'More',
    editProfile: 'Edit Profile →',
    deactivate: 'Deactivate Account',
    sections: Object.freeze({
      account: 'Account',
      support: 'Support',
      app: 'App',
    }),
    items: Object.freeze({
      premium: 'Premium Account',
      complaints: 'My Complaints',
      listings: 'My Listings',
      security: 'Security & Privacy',
      help: 'Help & Support',
      privacy: 'Privacy Policy',
      terms: 'Terms of Service',
      notifications: 'Notifications',
      scamBlock: 'Scam Block',
      spamBlock: 'Spam Block',
    }),
  }),

  errors: Object.freeze({
    generic: 'Something went wrong. Please try again.',
    network: 'No internet connection.',
    invalidPhone: 'Enter a valid phone number.',
    invalidEmail: 'Enter a valid email address.',
    otpInvalid: 'Incorrect OTP. Please try again.',
    otpExpired: 'OTP expired. Request a new one.',
    fileTooLarge: 'File is too large.',
    maxUploads: 'Maximum 6 files allowed.',
    permissionDenied: 'Permission denied.',
    locationUnavailable: 'Unable to fetch your location.',
  }),

  toasts: Object.freeze({
    reportSubmitted: 'Report submitted. The scammer will be notified.',
    profileSaved: 'Profile saved.',
    listingPosted: 'Listing posted.',
    listingDraftSaved: 'Draft saved.',
    messageSent: 'Message sent.',
    copiedToClipboard: 'Copied to clipboard.',
    signedOut: 'Signed out.',
  }),

  tabs: Object.freeze({
    dialer: 'Dialer',
    recents: 'Recents',
    scam: 'Scam',
    listings: 'Listings',
    more: 'More',
  }),
});

export default STRINGS;
